<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.scijava</groupId>
		<artifactId>pom-scijava</artifactId>
		<version>43.0.0</version>
		<relativePath />
	</parent>

	<groupId>org.careamics</groupId>
	<artifactId>CAREamics_Fiji</artifactId>
	<version>1.0-SNAPSHOT</version>

	<name>careamics-fiji</name>
	<description>CAREamics Fiji plugin based on Appose.</description>
	<url>https://careamics.github.io/</url>
	<inceptionYear>2026</inceptionYear>
	<organization>
		<name>CAREamics</name>
		<url>https://github.com/CAREamics/</url>
	</organization>
	<licenses>
		<license>
			<name>BSD 3-Clause License</name>
			<url>https://opensource.org/licenses/BSD-3-Clause</url>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<developers>
		<developer>
			<id>mese79</id>
			<name>Mehdi Seifi</name>
			<url>https://github.com/mese79</url>
			<roles>
				<role>lead</role>
				<role>developer</role>
				<role>debugger</role>
				<role>reviewer</role>
				<role>support</role>
				<role>maintainer</role>
			</roles>
		</developer>
	</developers>

	<contributors>
		<contributor>
			<name>Mehdi Seifi</name>
			<url>https://github.com/mese79</url>
			<properties>
				<id>mese79</id>
			</properties>
		</contributor>
	</contributors>

	<mailingLists>
		<mailingList>
			<name>ImageJ Forum</name>
			<archive>http://forum.imagej.net/</archive>
		</mailingList>
	</mailingLists>

	<scm>
		<connection>scm:git:git://github.com/CAREamics/careamics-fiji</connection>
		<developerConnection>scm:git:git@github.com:CAREamics/careamics-fiji</developerConnection>
		<tag>HEAD</tag>
		<url>https://github.com/CAREamics/careamics-fiji</url>
	</scm>

	<issueManagement>
		<system>GitHub Issues</system>
		<url>https://github.com/CAREamics/careamics-fiji/issues</url>
	</issueManagement>

	<ciManagement>
		<system>None</system>
	</ciManagement>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.release>17</maven.compiler.release>

		<package-name>org.careamics.fiji</package-name>
		<main-class>org.careamics.fiji.App</main-class>
		<license.licenseName>bsd_3_clause</license.licenseName>
		<license.copyrightOwners>CAREamics Team</license.copyrightOwners>

		<!-- Use Java 21. -->
		<scijava.jvm.version>21</scijava.jvm.version>
		<scijava.jvm.build.version>[21,)</scijava.jvm.build.version>

		<appose.version>0.12.0</appose.version>
		<imglib2-appose.version>0.9.0</imglib2-appose.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.junit</groupId>
				<artifactId>junit-bom</artifactId>
				<version>5.11.0</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<!-- ImageJ 1.x dependency -->
		<dependency>
			<groupId>net.imagej</groupId>
			<artifactId>ij</artifactId>
		</dependency>

		<!-- Appose dependencies -->
		<dependency>
			<groupId>org.apposed</groupId>
			<artifactId>appose</artifactId>
			<version>${appose.version}</version>
		</dependency>

		<!-- ImgLib2 dependencies -->
		<dependency>
			<groupId>net.imglib2</groupId>
			<artifactId>imglib2-appose</artifactId>
			<version>${imglib2-appose.version}</version>
		</dependency>
		<dependency>
			<groupId>net.imglib2</groupId>
			<artifactId>imglib2-ij</artifactId>
		</dependency>

		<dependency>
			<groupId>net.imagej</groupId>
			<artifactId>imagej</artifactId>
		</dependency>

		<dependency>
			<groupId>org.jfree</groupId>
			<artifactId>jfreechart</artifactId>
			<version>1.5.6</version>
		</dependency>

	</dependencies>

	<repositories>
		<repository>
			<id>scijava.public</id>
			<url>https://maven.scijava.org/content/groups/public</url>
		</repository>
	</repositories>

	<!-- <build> -->
	<!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
	<!-- <pluginManagement> -->
	<!-- <plugins> -->
	<!-- clean lifecycle, see
	https://maven.apache.org/ref/current/maven-core/lifecycles.html#clean_Lifecycle -->
	<!-- <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.4.0</version>
        </plugin> -->
	<!-- default lifecycle, jar packaging: see
	https://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
	<!-- <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.3.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.13.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>3.3.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.4.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>3.1.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>3.1.2</version>
        </plugin> -->
	<!-- site lifecycle, see
	https://maven.apache.org/ref/current/maven-core/lifecycles.html#site_Lifecycle -->
	<!-- <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.12.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.6.1</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build> -->

</project>