[project]
name = "careamics-appose"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mehdi Seifi", email = "mehdiseifi@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "appose>=0.12.0",
    "careamics==0.3.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "pyrefly>=1.2.0",
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]
